# Generated by Django 2.1.5 on 2019-02-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_lst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('lst', 'text')},
        ),
    ]
